- url: 'https://www.zara.com/se/sv/dam/nyheter/l%C3%A5ng-kimono-i-silk-och-sammet-c840002p4786556.html'
  price_selector: '.right-container div.price._product-price > span'
  parse_type: 'zara'
  type: 'price_change'

- url: 'https://thepihut.com/products/the-magpi-57?variant=33916909649'
  price_selector: '#AddToCartForm > span'
  parse_type: 'noop'
  type: 'stock_change'
